### ISSUE TITLE
Concept of page from the original book

### ISSUE THREAD

**Issue by angoca** [rodneykrick/db2-sql-cookbook#1]
The book has internal references to specific pages; however, as the book is now online, it should be replaced to sections. I do not know how to do it in asciidoc, and for this reason I created this issue instead.

**Comment by rodneykrick** [comment]
Thank you Andres. I tried to remove all the page references and replace with section references. I'm sure I didn't manage to replace all. I'll give a look on it again. 
Section references in asciidoc are easy to implement.  You just put a [[section.id]] before the title and reference it using <<section.id>> in the text.

**Comment by rodneykrick** [comment]
I've searched all the pages and replaced the page references with section references. I hope I found all of them.

**Comment by rodneykrick** [comment]
Page references were removed and replaced with the sections of the book.
