### ISSUE TITLE
References to figures

### ISSUE THREAD

**Issue by angoca** [rodneykrick/db2-sql-cookbook#5]
The new document does not include figures, however the text makes references to many figures.

**Comment by rodneykrick** [comment]
In this version I really forget to check the references to the "figures". I only replaced the references to "see page". I'll check it. Thank you!

**Comment by rodneykrick** [comment]
I hope I have found all of them and replaced with a link. Changes are checked in.

**Comment by rodneykrick** [comment]
No more figures referenced.
